import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavBar } from "../components/Navbar";
import RouteTransition from "../components/Animations/RouteTransition";
import { Footer } from "../components/Footer";
import Provider from "../components/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-dvh flex flex-col max-w-screen justify-between bg-black">
          <NavBar />
          <RouteTransition>
            <Provider>
              <div className="flex min-h-full min-w-screen">{children}</div>
            </Provider>
          </RouteTransition>
          <Footer />
        </div>
      </body>
    </html>
  );
}
